# theme
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: "OBL: An Intuitive Guide"
description: "An explanation of OBL from a user's perspective."

# site

announcement: true

collections:
  authors:
    output: true
  cases:
    output: true
  cases_by_optimal:
    output: true
  faces:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "cases"
    values:
      layout: "case"
  - scope:
      path: ""
      type: "cases_by_optimal"
    values:
      layout: "case_by_optimal"
  - scope:
      path: ""
      type: "faces"
    values:
      layout: "face"
  - scope:
      path: ""
    values:
      layout: "default"
